CREATE SEQUENCE seq_dw_reason  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_company START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_branch  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_address START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_promo   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_item    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_dw_cust    START WITH 1 INCREMENT BY 1 NOCACHE;