/* ============================================================================
   TASK 1(b) — PHYSICAL DESIGN
   Sales & Returns Data Warehouse — Fact Constellation with Conformed Dimensions
   Target DBMS : Oracle 12c or later
   Based on    : Task 1(a) corrected star (galaxy) schema
   ----------------------------------------------------------------------------
   Build order : dimensions -> facts (parents before children)
   Contents    : 1. Clean-up          2. Surrogate-key sequences
                 3. Dimension tables  4. Fact tables
                 5. FK indexes        6. Seed rows (Unknown / No Promotion)
                 7. Role-playing date views
   ============================================================================ */


/* ============================================================================
   1. CLEAN-UP  (drop children first so FK dependencies are not violated)
   NOTE: on a first, empty run these statements raise ORA-00942 / ORA-02289
         ("object does not exist"). That is expected — continue past them.
   ============================================================================ */
DROP VIEW ORDER_DATE_DIM;
DROP VIEW RETURN_DATE_DIM;

DROP TABLE RETURNS_FACT      CASCADE CONSTRAINTS PURGE;
DROP TABLE SALES_FACT        CASCADE CONSTRAINTS PURGE;
DROP TABLE RETURN_REASON_DIM CASCADE CONSTRAINTS PURGE;
DROP TABLE PROMOTION_DIM     CASCADE CONSTRAINTS PURGE;
DROP TABLE BRANCH_DIM        CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER_DIM      CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCT_DIM       CASCADE CONSTRAINTS PURGE;
DROP TABLE DATE_DIM          CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE SEQ_PRODUCT_KEY;
DROP SEQUENCE SEQ_CUSTOMER_KEY;
DROP SEQUENCE SEQ_BRANCH_KEY;
DROP SEQUENCE SEQ_PROMO_KEY;
DROP SEQUENCE SEQ_REASON_KEY;


/* ============================================================================
   2. SURROGATE-KEY SEQUENCES
   Surrogate keys are generated by the ETL, never by the source system, so that
   the warehouse is insulated from source-key reuse and format changes.
   Sequences start at 1 because 0 and -1 are reserved for the seeded rows.
   ============================================================================ */
CREATE SEQUENCE SEQ_PRODUCT_KEY  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMER_KEY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BRANCH_KEY   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROMO_KEY    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REASON_KEY   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* ============================================================================
   3. DIMENSION TABLES
   ============================================================================ */

/* ----------------------------------------------------------------------------
   3.1 DATE_DIM — conformed, role-playing dimension (order date / return date)
   Smart integer key YYYYMMDD: joins on a 4-byte NUMBER instead of a DATE, and
   lets the fact tables be range-partitioned on the key if volumes require it.
   -------------------------------------------------------------------------- */
CREATE TABLE DATE_DIM (
    date_key            NUMBER(8)      NOT NULL,
    cal_date            DATE           NOT NULL,
    full_desc           VARCHAR2(30)   NOT NULL,
    day_week            VARCHAR2(9)    NOT NULL,
    day_num_month       NUMBER(2)      NOT NULL,
    day_num_year        NUMBER(3)      NOT NULL,
    last_day_ind        CHAR(1)        DEFAULT 'N' NOT NULL,
    cal_week_end_date   DATE           NOT NULL,
    cal_week_year       VARCHAR2(8)    NOT NULL,
    cal_month_name      VARCHAR2(9)    NOT NULL,
    cal_month_year      VARCHAR2(9)    NOT NULL,
    cal_year_month      CHAR(7)        NOT NULL,
    cal_quarter         CHAR(2)        NOT NULL,
    cal_year_quarter    CHAR(7)        NOT NULL,
    cal_year            NUMBER(4)      NOT NULL,
    holiday_ind         CHAR(1)        DEFAULT 'N'    NOT NULL,
    weekday_ind         CHAR(1)        DEFAULT 'Y'    NOT NULL,
    festive_event       VARCHAR2(30)   DEFAULT 'None' NOT NULL,
    CONSTRAINT pk_date_dim        PRIMARY KEY (date_key),
    CONSTRAINT uq_date_cal_date   UNIQUE      (cal_date),
    CONSTRAINT ck_date_last_day   CHECK (last_day_ind IN ('Y','N')),
    CONSTRAINT ck_date_holiday    CHECK (holiday_ind  IN ('Y','N')),
    CONSTRAINT ck_date_weekday    CHECK (weekday_ind  IN ('Y','N')),
    CONSTRAINT ck_date_quarter    CHECK (cal_quarter  IN ('Q1','Q2','Q3','Q4')),
    CONSTRAINT ck_date_daynum_m   CHECK (day_num_month BETWEEN 1 AND 31),
    CONSTRAINT ck_date_daynum_y   CHECK (day_num_year  BETWEEN 1 AND 366),
    CONSTRAINT ck_date_key_range  CHECK (date_key = -1 OR date_key BETWEEN 19000101 AND 99991231)
);

/* ----------------------------------------------------------------------------
   3.2 PRODUCT_DIM — SCD Type 1 (overwrite; no history of descriptive changes)
   item_id is the natural key: UNIQUE, but NOT the primary key.
   -------------------------------------------------------------------------- */
CREATE TABLE PRODUCT_DIM (
    product_key         NUMBER(10)     NOT NULL,
    item_id             VARCHAR2(20)   NOT NULL,
    item_name           VARCHAR2(100)  NOT NULL,
    item_status         VARCHAR2(15)   DEFAULT 'Active' NOT NULL,
    current_unit_price  NUMBER(10,2)   DEFAULT 0 NOT NULL,
    category_name       VARCHAR2(50)   DEFAULT 'Unknown' NOT NULL,
    supplier_name       VARCHAR2(100)  DEFAULT 'Unknown' NOT NULL,
    supplier_contact_no VARCHAR2(20),
    etl_batch_id        NUMBER(10)     NOT NULL,
    load_dt             DATE           DEFAULT SYSDATE NOT NULL,
    dq_flag             CHAR(1)        DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_product_dim      PRIMARY KEY (product_key),
    CONSTRAINT uq_product_item_id  UNIQUE      (item_id),
    CONSTRAINT ck_product_status   CHECK (item_status IN ('Active','Inactive','Discontinued','Unknown')),
    CONSTRAINT ck_product_price    CHECK (current_unit_price >= 0),
    CONSTRAINT ck_product_dq       CHECK (dq_flag IN ('C','S','E'))   /* Clean / Suspect / Error */
);

/* ----------------------------------------------------------------------------
   3.3 CUSTOMER_DIM — *** SCD TYPE 2 *** (required by the task)
   History is tracked by adding a new row whenever a tracked attribute changes.
   Tracked attributes: customer_status, member_flag, membership_type,
   membership_fee, email.
   Because one customer_id may own many rows, customer_id alone is deliberately
   NOT unique; the business uniqueness rule is (customer_id, effective_start_date).
   The open row carries effective_end_date = 9999-12-31 and is_current_flag = 'Y'.
   -------------------------------------------------------------------------- */
CREATE TABLE CUSTOMER_DIM (
    customer_key         NUMBER(10)    NOT NULL,
    customer_id          VARCHAR2(20)  NOT NULL,
    customer_name        VARCHAR2(100) NOT NULL,
    ic_no                VARCHAR2(20),
    email                VARCHAR2(100),
    customer_status      VARCHAR2(15)  DEFAULT 'Active' NOT NULL,
    member_flag          CHAR(1)       DEFAULT 'N' NOT NULL,
    membership_type      VARCHAR2(20)  DEFAULT 'None' NOT NULL,
    membership_fee       NUMBER(8,2)   DEFAULT 0 NOT NULL,
    effective_start_date DATE          DEFAULT SYSDATE NOT NULL,
    effective_end_date   DATE          DEFAULT DATE '9999-12-31' NOT NULL,
    is_current_flag      CHAR(1)       DEFAULT 'Y' NOT NULL,
    version_no           NUMBER(4)     DEFAULT 1 NOT NULL,
    etl_batch_id         NUMBER(10)    NOT NULL,
    load_dt              DATE          DEFAULT SYSDATE NOT NULL,
    dq_flag              CHAR(1)       DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_customer_dim       PRIMARY KEY (customer_key),
    CONSTRAINT uq_customer_version   UNIQUE      (customer_id, effective_start_date),
    CONSTRAINT ck_customer_status    CHECK (customer_status IN ('Active','Inactive','Closed','Unknown')),
    CONSTRAINT ck_customer_member    CHECK (member_flag     IN ('Y','N')),
    CONSTRAINT ck_customer_current   CHECK (is_current_flag IN ('Y','N')),
    CONSTRAINT ck_customer_memtype   CHECK (membership_type IN ('None','Basic','Silver','Gold','Platinum','Unknown')),
    CONSTRAINT ck_customer_fee       CHECK (membership_fee >= 0),
    CONSTRAINT ck_customer_version   CHECK (version_no >= 1),
    CONSTRAINT ck_customer_dates     CHECK (effective_end_date >= effective_start_date),
    /* an open (current) row must carry the high-date end marker, and vice versa */
    CONSTRAINT ck_customer_open_row  CHECK ( (is_current_flag = 'Y' AND effective_end_date = DATE '9999-12-31')
                                          OR (is_current_flag = 'N' AND effective_end_date <  DATE '9999-12-31') ),
    CONSTRAINT ck_customer_dq        CHECK (dq_flag IN ('C','S','E'))
);

/* At most ONE current row per customer. A function-based unique index is used
   because the rule applies only to rows where is_current_flag = 'Y'.           */
CREATE UNIQUE INDEX uix_customer_one_current
    ON CUSTOMER_DIM (CASE WHEN is_current_flag = 'Y' THEN customer_id END);

/* ----------------------------------------------------------------------------
   3.4 BRANCH_DIM — SCD Type 1
   -------------------------------------------------------------------------- */
CREATE TABLE BRANCH_DIM (
    branch_key    NUMBER(10)    NOT NULL,
    branch_id     VARCHAR2(20)  NOT NULL,
    branch_name   VARCHAR2(100) NOT NULL,
    city          VARCHAR2(50)  DEFAULT 'Unknown' NOT NULL,
    state         VARCHAR2(50)  DEFAULT 'Unknown' NOT NULL,
    region        VARCHAR2(20)  DEFAULT 'Unknown' NOT NULL,
    contact_no    VARCHAR2(20),
    etl_batch_id  NUMBER(10)    NOT NULL,
    load_dt       DATE          DEFAULT SYSDATE NOT NULL,
    dq_flag       CHAR(1)       DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_branch_dim     PRIMARY KEY (branch_key),
    CONSTRAINT uq_branch_id      UNIQUE      (branch_id),
    CONSTRAINT ck_branch_region  CHECK (region IN ('Northern','Central','Southern','East Coast','East Malaysia','Unknown')),
    CONSTRAINT ck_branch_dq      CHECK (dq_flag IN ('C','S','E'))
);

/* ----------------------------------------------------------------------------
   3.5 PROMOTION_DIM — SCD Type 1
   promo_key = 0 is reserved for 'No Promotion' so that a non-promotional sale
   is never confused with an unresolvable promotion reference (key -1).
   promo_duration_days is a VIRTUAL column: derived, never stored, never stale.
   -------------------------------------------------------------------------- */
CREATE TABLE PROMOTION_DIM (
    promo_key           NUMBER(10)    NOT NULL,
    promotion_id        VARCHAR2(20)  NOT NULL,
    promo_name          VARCHAR2(100) NOT NULL,
    discount_type       VARCHAR2(20)  DEFAULT 'None' NOT NULL,
    discount_value      NUMBER(8,2)   DEFAULT 0 NOT NULL,
    promo_start_date    DATE,
    promo_end_date      DATE,
    promo_status        VARCHAR2(15)  DEFAULT 'Inactive' NOT NULL,
    promo_duration_days NUMBER(6) GENERATED ALWAYS AS
                        (promo_end_date - promo_start_date + 1) VIRTUAL,
    etl_batch_id        NUMBER(10)    NOT NULL,
    load_dt             DATE          DEFAULT SYSDATE NOT NULL,
    dq_flag             CHAR(1)       DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_promotion_dim     PRIMARY KEY (promo_key),
    CONSTRAINT uq_promotion_id      UNIQUE      (promotion_id),
    CONSTRAINT ck_promo_disc_type   CHECK (discount_type IN ('Percentage','Fixed Amount','Buy X Get Y','None','Unknown')),
    CONSTRAINT ck_promo_disc_value  CHECK (discount_value >= 0),
    CONSTRAINT ck_promo_pct_range   CHECK (discount_type <> 'Percentage' OR discount_value BETWEEN 0 AND 100),
    CONSTRAINT ck_promo_status      CHECK (promo_status IN ('Active','Expired','Planned','Inactive','Unknown')),
    CONSTRAINT ck_promo_dates       CHECK (promo_end_date >= promo_start_date),
    CONSTRAINT ck_promo_dq          CHECK (dq_flag IN ('C','S','E'))
);

/* ----------------------------------------------------------------------------
   3.6 RETURN_REASON_DIM — SCD Type 1, used only by RETURNS_FACT
   -------------------------------------------------------------------------- */
CREATE TABLE RETURN_REASON_DIM (
    reason_key      NUMBER(10)    NOT NULL,
    reason_id       VARCHAR2(20)  NOT NULL,
    reason_name     VARCHAR2(50)  NOT NULL,
    reason_category VARCHAR2(30)  DEFAULT 'Unknown' NOT NULL,
    etl_batch_id    NUMBER(10)    NOT NULL,
    load_dt         DATE          DEFAULT SYSDATE NOT NULL,
    dq_flag         CHAR(1)       DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_return_reason_dim PRIMARY KEY (reason_key),
    CONSTRAINT uq_reason_id         UNIQUE      (reason_id),
    CONSTRAINT ck_reason_category   CHECK (reason_category IN ('Product Quality','Customer Preference','Logistics','Pricing','Unknown')),
    CONSTRAINT ck_reason_dq         CHECK (dq_flag IN ('C','S','E'))
);


/* ============================================================================
   4. FACT TABLES
   ============================================================================ */

/* ----------------------------------------------------------------------------
   4.1 SALES_FACT
   Grain: ONE ROW PER ITEM LINE PER ORDER.
   The primary key (order_no, product_key) is the minimal key that enforces that
   grain. order_no is a degenerate dimension — an operational reference number
   with no attributes of its own, so it is kept in the fact table.
   All other dimension keys are mandatory, indexed FKs but are NOT part of the PK.
   -------------------------------------------------------------------------- */
CREATE TABLE SALES_FACT (
    order_no        VARCHAR2(20)  NOT NULL,     /* DD — degenerate dimension */
    product_key     NUMBER(10)    NOT NULL,
    order_date_key  NUMBER(8)     NOT NULL,
    customer_key    NUMBER(10)    NOT NULL,
    branch_key      NUMBER(10)    NOT NULL,
    promo_key       NUMBER(10)    DEFAULT 0 NOT NULL,
    order_type      VARCHAR2(15)  DEFAULT 'In-Store' NOT NULL,
    order_hour      NUMBER(2)     NOT NULL,
    quantity        NUMBER(6)     NOT NULL,     /* additive      */
    unit_price      NUMBER(10,2)  NOT NULL,     /* non-additive  */
    gross_sales_amt NUMBER(12,2)  NOT NULL,     /* additive      */
    discount_amt    NUMBER(12,2)  DEFAULT 0 NOT NULL,  /* additive */
    net_sales_amt   NUMBER(12,2)  NOT NULL,     /* additive      */
    etl_batch_id    NUMBER(10)    NOT NULL,
    load_dt         DATE          DEFAULT SYSDATE NOT NULL,
    dq_flag         CHAR(1)       DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_sales_fact      PRIMARY KEY (order_no, product_key),
    CONSTRAINT fk_sales_product   FOREIGN KEY (product_key)    REFERENCES PRODUCT_DIM   (product_key),
    CONSTRAINT fk_sales_date      FOREIGN KEY (order_date_key) REFERENCES DATE_DIM      (date_key),
    CONSTRAINT fk_sales_customer  FOREIGN KEY (customer_key)   REFERENCES CUSTOMER_DIM  (customer_key),
    CONSTRAINT fk_sales_branch    FOREIGN KEY (branch_key)     REFERENCES BRANCH_DIM    (branch_key),
    CONSTRAINT fk_sales_promo     FOREIGN KEY (promo_key)      REFERENCES PROMOTION_DIM (promo_key),
    CONSTRAINT ck_sales_type      CHECK (order_type IN ('In-Store','Online','Phone','Mobile App','Unknown')),
    CONSTRAINT ck_sales_hour      CHECK (order_hour BETWEEN 0 AND 23),
    CONSTRAINT ck_sales_qty       CHECK (quantity > 0),
    CONSTRAINT ck_sales_price     CHECK (unit_price   >= 0),
    CONSTRAINT ck_sales_gross     CHECK (gross_sales_amt >= 0),
    CONSTRAINT ck_sales_disc      CHECK (discount_amt BETWEEN 0 AND gross_sales_amt),
    CONSTRAINT ck_sales_net       CHECK (net_sales_amt = gross_sales_amt - discount_amt),
    CONSTRAINT ck_sales_dq        CHECK (dq_flag IN ('C','S','E'))
);

/* ----------------------------------------------------------------------------
   4.2 RETURNS_FACT
   Grain: ONE ROW PER RETURNED ITEM LINE.
   PK (return_id, product_key). order_no is carried as a second degenerate
   dimension so a return can be traced back to its originating sales line.
   DATE_DIM is referenced twice (role-playing): return_date_key and
   order_date_key.
   -------------------------------------------------------------------------- */
CREATE TABLE RETURNS_FACT (
    return_id        VARCHAR2(20) NOT NULL,     /* DD */
    product_key      NUMBER(10)   NOT NULL,
    return_date_key  NUMBER(8)    NOT NULL,
    order_date_key   NUMBER(8)    NOT NULL,     /* role-playing DATE_DIM */
    customer_key     NUMBER(10)   NOT NULL,
    branch_key       NUMBER(10)   NOT NULL,
    reason_key       NUMBER(10)   NOT NULL,
    promo_key        NUMBER(10)   DEFAULT 0 NOT NULL,
    order_no         VARCHAR2(20) NOT NULL,     /* DD */
    return_status    VARCHAR2(15) DEFAULT 'Pending' NOT NULL,
    quantity_returned NUMBER(6)   NOT NULL,     /* additive     */
    refund_amount    NUMBER(12,2) DEFAULT 0 NOT NULL,  /* additive */
    days_to_return   NUMBER(5)    NOT NULL,     /* non-additive */
    etl_batch_id     NUMBER(10)   NOT NULL,
    load_dt          DATE         DEFAULT SYSDATE NOT NULL,
    dq_flag          CHAR(1)      DEFAULT 'C' NOT NULL,
    CONSTRAINT pk_returns_fact       PRIMARY KEY (return_id, product_key),
    CONSTRAINT fk_ret_product        FOREIGN KEY (product_key)     REFERENCES PRODUCT_DIM       (product_key),
    CONSTRAINT fk_ret_return_date    FOREIGN KEY (return_date_key) REFERENCES DATE_DIM          (date_key),
    CONSTRAINT fk_ret_order_date     FOREIGN KEY (order_date_key)  REFERENCES DATE_DIM          (date_key),
    CONSTRAINT fk_ret_customer       FOREIGN KEY (customer_key)    REFERENCES CUSTOMER_DIM      (customer_key),
    CONSTRAINT fk_ret_branch         FOREIGN KEY (branch_key)      REFERENCES BRANCH_DIM        (branch_key),
    CONSTRAINT fk_ret_reason         FOREIGN KEY (reason_key)      REFERENCES RETURN_REASON_DIM (reason_key),
    CONSTRAINT fk_ret_promo          FOREIGN KEY (promo_key)       REFERENCES PROMOTION_DIM     (promo_key),
    CONSTRAINT ck_ret_status         CHECK (return_status IN ('Pending','Approved','Rejected','Refunded','Unknown')),
    CONSTRAINT ck_ret_qty            CHECK (quantity_returned > 0),
    CONSTRAINT ck_ret_refund         CHECK (refund_amount >= 0),
    CONSTRAINT ck_ret_days           CHECK (days_to_return >= 0),
    /* a return cannot precede its order — the -1 escape allows an Unknown date */
    CONSTRAINT ck_ret_date_order     CHECK (return_date_key = -1 OR order_date_key = -1
                                            OR return_date_key >= order_date_key),
    CONSTRAINT ck_ret_dq             CHECK (dq_flag IN ('C','S','E'))
);


/* ============================================================================
   5. INDEXES ON FOREIGN KEYS
   Oracle indexes PK/UNIQUE columns automatically but NOT foreign keys.
   Each FK is indexed so that star-transformation joins and dimension-driven
   filters do not force a full scan of the fact tables.
   ============================================================================ */
CREATE INDEX ix_sales_product   ON SALES_FACT   (product_key);
CREATE INDEX ix_sales_date      ON SALES_FACT   (order_date_key);
CREATE INDEX ix_sales_customer  ON SALES_FACT   (customer_key);
CREATE INDEX ix_sales_branch    ON SALES_FACT   (branch_key);
CREATE INDEX ix_sales_promo     ON SALES_FACT   (promo_key);

CREATE INDEX ix_ret_product     ON RETURNS_FACT (product_key);
CREATE INDEX ix_ret_retdate     ON RETURNS_FACT (return_date_key);
CREATE INDEX ix_ret_orddate     ON RETURNS_FACT (order_date_key);
CREATE INDEX ix_ret_customer    ON RETURNS_FACT (customer_key);
CREATE INDEX ix_ret_branch      ON RETURNS_FACT (branch_key);
CREATE INDEX ix_ret_reason      ON RETURNS_FACT (reason_key);
CREATE INDEX ix_ret_promo       ON RETURNS_FACT (promo_key);
CREATE INDEX ix_ret_order_no    ON RETURNS_FACT (order_no);   /* sales <-> returns drill-across */

/* Natural-key lookup index used by the SCD Type 2 ETL */
CREATE INDEX ix_customer_nk     ON CUSTOMER_DIM (customer_id, effective_start_date);


/* ============================================================================
   6. SEED ROWS
   Every dimension carries key -1 = 'Unknown' so that a fact row with dirty or
   missing source data can still be loaded without breaking referential
   integrity (early-arriving-fact handling).
   PROMOTION_DIM additionally seeds key 0 = 'No Promotion'.
   ============================================================================ */
INSERT INTO DATE_DIM VALUES
  (-1, DATE '9999-12-31', 'Unknown Date', 'Unknown', 1, 1, 'N',
   DATE '9999-12-31', 'Unknown', 'Unknown', 'Unknown', 'UNKNOWN',
   'Q1', 'UNKNOWN', 9999, 'N', 'N', 'None');

INSERT INTO PRODUCT_DIM
  (product_key, item_id, item_name, item_status, current_unit_price,
   category_name, supplier_name, supplier_contact_no, etl_batch_id, dq_flag)
VALUES (-1, 'UNKNOWN', 'Unknown Product', 'Unknown', 0,
        'Unknown', 'Unknown', NULL, 0, 'C');

INSERT INTO CUSTOMER_DIM
  (customer_key, customer_id, customer_name, ic_no, email, customer_status,
   member_flag, membership_type, membership_fee, effective_start_date,
   effective_end_date, is_current_flag, version_no, etl_batch_id, dq_flag)
VALUES (-1, 'UNKNOWN', 'Unknown Customer', NULL, NULL, 'Unknown',
        'N', 'Unknown', 0, DATE '1900-01-01',
        DATE '9999-12-31', 'Y', 1, 0, 'C');

INSERT INTO BRANCH_DIM
  (branch_key, branch_id, branch_name, city, state, region, contact_no,
   etl_batch_id, dq_flag)
VALUES (-1, 'UNKNOWN', 'Unknown Branch', 'Unknown', 'Unknown', 'Unknown', NULL, 0, 'C');

INSERT INTO PROMOTION_DIM
  (promo_key, promotion_id, promo_name, discount_type, discount_value,
   promo_start_date, promo_end_date, promo_status, etl_batch_id, dq_flag)
VALUES (0, 'NOPROMO', 'No Promotion', 'None', 0, NULL, NULL, 'Inactive', 0, 'C');

INSERT INTO PROMOTION_DIM
  (promo_key, promotion_id, promo_name, discount_type, discount_value,
   promo_start_date, promo_end_date, promo_status, etl_batch_id, dq_flag)
VALUES (-1, 'UNKNOWN', 'Unknown Promotion', 'Unknown', 0, NULL, NULL, 'Unknown', 0, 'C');

INSERT INTO RETURN_REASON_DIM
  (reason_key, reason_id, reason_name, reason_category, etl_batch_id, dq_flag)
VALUES (-1, 'UNKNOWN', 'Unknown Reason', 'Unknown', 0, 'C');

COMMIT;


/* ============================================================================
   7. ROLE-PLAYING VIEWS
   DATE_DIM is referenced three times across the two facts. Exposing it to the
   BI layer through two aliased views removes the self-join ambiguity for end
   users without duplicating the underlying data.
   ============================================================================ */
CREATE OR REPLACE VIEW ORDER_DATE_DIM AS
SELECT date_key          AS order_date_key,
       cal_date          AS order_date,
       full_desc         AS order_full_desc,
       day_week          AS order_day_week,
       cal_week_year     AS order_week_year,
       cal_month_name    AS order_month_name,
       cal_year_month    AS order_year_month,
       cal_quarter       AS order_quarter,
       cal_year_quarter  AS order_year_quarter,
       cal_year          AS order_year,
       holiday_ind       AS order_holiday_ind,
       weekday_ind       AS order_weekday_ind,
       festive_event     AS order_festive_event
FROM   DATE_DIM;

CREATE OR REPLACE VIEW RETURN_DATE_DIM AS
SELECT date_key          AS return_date_key,
       cal_date          AS return_date,
       full_desc         AS return_full_desc,
       day_week          AS return_day_week,
       cal_week_year     AS return_week_year,
       cal_month_name    AS return_month_name,
       cal_year_month    AS return_year_month,
       cal_quarter       AS return_quarter,
       cal_year_quarter  AS return_year_quarter,
       cal_year          AS return_year,
       holiday_ind       AS return_holiday_ind,
       weekday_ind       AS return_weekday_ind,
       festive_event     AS return_festive_event
FROM   DATE_DIM;

/* ======================== END OF TASK 1(b) SCRIPT ========================== */
