-- ============================================================================
--  BMIT3003 DATA WAREHOUSE TECHNOLOGY - ASSIGNMENT
--  TASK 1(b) : PHYSICAL DESIGN
--  System    : 88 Speedmart Grocery - Sales, Returns, Delivery & Loyalty
--              Data Warehouse
--  DBMS      : Oracle
-- ----------------------------------------------------------------------------
--  STRUCTURE : 8 dimension tables + 4 fact tables (fact constellation)
--              CUSTOMER_DIM is a Slowly Changing Dimension Type 2.
--
--  CONVENTION: The warehouse is a SELF-CONTAINED schema owned by the DW user.
--              The operational tables built by Task2_DDL.sql are owned by a
--              SEPARATE Oracle user, so the warehouse declares NO foreign key
--              into that schema.  Every foreign key below points at another
--              warehouse table (fact -> dimension).
--
--              Each dimension still stores its operational identifier for
--              lineage and for ETL matching, as a NOT NULL UNIQUE column.
--              Referential integrity back to the operational system is
--              enforced by the ETL and documented in the source-to-target
--              mapping, not by a database constraint.  This is deliberate:
--              a Type 2 dimension must retain history that the operational
--              system has already deleted, which a foreign key would forbid.
--
--  NAMING    : snake_case throughout.
--
--  RESERVED IDENTIFIERS FOR SEEDED ROWS
--              Every dimension is seeded with one row keyed -1 representing
--              'Unknown', which uses the reserved operational identifier
--              'UNKN'.  PROMOTION_DIM additionally seeds a row keyed 0
--              representing 'No Promotion', which uses 'NONE'.
--
--  PREREQUISITE FOR TASK 2
--              The ETL reads the operational tables across schemas, so the
--              operational owner must first run:
--                  GRANT SELECT ON <table> TO dw;
--              for each of the 18 source tables.
-- ============================================================================

SET SERVEROUTPUT ON
SET LINESIZE 170
SET PAGESIZE 100

-- ----------------------------------------------------------------------------
--  Drop in reverse dependency order so the script can be re-run
-- ----------------------------------------------------------------------------
DROP TABLE point_fact            CASCADE CONSTRAINTS;
DROP TABLE delivery_fact         CASCADE CONSTRAINTS;
DROP TABLE return_fact           CASCADE CONSTRAINTS;
DROP TABLE sales_fact            CASCADE CONSTRAINTS;
DROP TABLE delivery_company_dim  CASCADE CONSTRAINTS;
DROP TABLE return_reason_dim     CASCADE CONSTRAINTS;
DROP TABLE promotion_dim         CASCADE CONSTRAINTS;
DROP TABLE address_dim           CASCADE CONSTRAINTS;
DROP TABLE branch_dim            CASCADE CONSTRAINTS;
DROP TABLE item_dim              CASCADE CONSTRAINTS;
DROP TABLE customer_dim          CASCADE CONSTRAINTS;
DROP TABLE date_dim              CASCADE CONSTRAINTS;


-- ============================================================================
--  SECTION 1 : DIMENSION TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
--  1. DATE_DIM  (Slowly Changing Dimension Type 0 - generated calendar)
--     Role-playing: referenced as order date, return date, delivery date and
--     point transaction date.  date_key is a "smart key" in YYYYMMDD form.
--     Seeded row: date_key = -1  ('Unknown', cal_date = 1900-01-01), used by
--     DELIVERY_FACT for deliveries that have not yet been despatched.
--     The calendar is generated by the ETL, not extracted from any source.
-- ----------------------------------------------------------------------------
CREATE TABLE date_dim
(
    date_key           NUMBER(8)     NOT NULL,
    cal_date           DATE          NOT NULL,
    full_desc          VARCHAR2(50)  NOT NULL,
    day_week           VARCHAR2(10)  NOT NULL,
    day_num_month      NUMBER(2)     NOT NULL,
    day_num_year       NUMBER(3)     NOT NULL,
    last_day_ind       CHAR(1)       DEFAULT 'N' NOT NULL,
    cal_week_end_date  DATE          NOT NULL,
    cal_week_year      NUMBER(2)     NOT NULL,
    cal_month_name     VARCHAR2(15)  NOT NULL,
    cal_month_year     NUMBER(2)     NOT NULL,
    cal_year_month     CHAR(7)       NOT NULL,
    cal_quarter        CHAR(2)       NOT NULL,
    cal_year_quarter   CHAR(7)       NOT NULL,
    cal_year           NUMBER(4)     NOT NULL,
    holiday_ind        CHAR(1)       DEFAULT 'N'    NOT NULL,
    weekday_ind        CHAR(1)       DEFAULT 'Y'    NOT NULL,
    festive_event      VARCHAR2(50)  DEFAULT 'None' NOT NULL,
    etl_batch_id       NUMBER(8)     NOT NULL,
    etl_load_dt        DATE          DEFAULT SYSDATE NOT NULL,
    etl_update_dt      DATE,
    dq_flag            CHAR(1)       DEFAULT 'V'    NOT NULL,
    CONSTRAINT date_dim_pk PRIMARY KEY (date_key),
    CONSTRAINT chk_date_dim_lastday CHECK (last_day_ind IN ('Y','N')),
    CONSTRAINT chk_date_dim_holiday CHECK (holiday_ind  IN ('Y','N')),
    CONSTRAINT chk_date_dim_weekday CHECK (weekday_ind  IN ('Y','N')),
    CONSTRAINT chk_date_dim_quarter CHECK (cal_quarter  IN ('Q1','Q2','Q3','Q4')),
    CONSTRAINT chk_date_dim_dqflag  CHECK (dq_flag      IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  2. CUSTOMER_DIM  ***  SLOWLY CHANGING DIMENSION TYPE 2  ***
--     Source : Customer + Member + MembershipType
--     Member is a 1:1 subtype of Customer, so members and walk-in non-members
--     share one dimension and are separated by member_flag.
--
--     Type 2 (a new version row is created)  : customer_status, member_flag,
--                                              membership_type
--     Type 1 (the existing row is overwritten): customer_name, customer_ic,
--                                              customer_email, membership_expiry
--
--     customer_id is intentionally NOT unique on its own - one customer has
--     many versions.  Uniqueness is (customer_id, effective_start_date).
--
--     Member.PointsBalance is deliberately excluded: it changes on every
--     transaction and would create a new version row per order.  The balance
--     is obtained instead by summing POINT_FACT.net_points.
-- ----------------------------------------------------------------------------
CREATE TABLE customer_dim
(
    customer_key          NUMBER(10)     NOT NULL,
    customer_id           VARCHAR2(5)    NOT NULL,                -- 'UNKN' on the -1 Unknown row
    customer_name         VARCHAR2(100)  DEFAULT 'Unknown'    NOT NULL,
    customer_ic           VARCHAR2(14)   DEFAULT 'Unknown'    NOT NULL,
    customer_email        VARCHAR2(100)  DEFAULT 'Unknown'    NOT NULL,
    customer_status       VARCHAR2(10)   DEFAULT 'Unknown'    NOT NULL,
    member_flag           CHAR(1)        DEFAULT 'N'          NOT NULL,
    membership_type       VARCHAR2(20)   DEFAULT 'Non-Member' NOT NULL,
    annual_fee            NUMBER(6,2)    DEFAULT 0            NOT NULL,
    point_earn_rate       NUMBER(4,2)    DEFAULT 0            NOT NULL,
    membership_expiry     DATE,
    effective_start_date  DATE           NOT NULL,
    effective_end_date    DATE           DEFAULT DATE '9999-12-31' NOT NULL,
    is_current_flag       CHAR(1)        DEFAULT 'Y'          NOT NULL,
    version_no            NUMBER(4)      DEFAULT 1            NOT NULL,
    etl_batch_id          NUMBER(8)      NOT NULL,
    etl_load_dt           DATE           DEFAULT SYSDATE      NOT NULL,
    etl_update_dt         DATE,
    dq_flag               CHAR(1)        DEFAULT 'V'          NOT NULL,
    CONSTRAINT customer_dim_pk PRIMARY KEY (customer_key),
    CONSTRAINT customer_dim_version_uq
        UNIQUE (customer_id, effective_start_date),
    CONSTRAINT chk_customer_dim_status
        CHECK (customer_status IN ('Active','Inactive','Unknown')),
    CONSTRAINT chk_customer_dim_member_flag
        CHECK (member_flag IN ('Y','N')),
    CONSTRAINT chk_customer_dim_type
        CHECK (membership_type IN ('Normal','VIP','Non-Member','Unknown')),
    CONSTRAINT chk_customer_dim_current
        CHECK (is_current_flag IN ('Y','N')),
    CONSTRAINT chk_customer_dim_fee     CHECK (annual_fee     >= 0),
    CONSTRAINT chk_customer_dim_rate    CHECK (point_earn_rate >= 0),
    CONSTRAINT chk_customer_dim_version CHECK (version_no    >= 1),
    CONSTRAINT chk_customer_dim_dates
        CHECK (effective_end_date >= effective_start_date),
    CONSTRAINT chk_customer_dim_dqflag  CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  3. ITEM_DIM  (Type 1)
--     Source : Item + Category + Supplier
--     Item -> Category and Item -> Supplier are both many-to-one, so both are
--     flattened into this dimension rather than snowflaked.
--     category_id and supplier_id are retained because Supplier.SupplierName
--     carries no UNIQUE constraint in the source and therefore cannot safely
--     be used on its own as a grouping key in Task 3.
-- ----------------------------------------------------------------------------
CREATE TABLE item_dim
(
    item_key             NUMBER(10)     NOT NULL,
    item_id              VARCHAR2(5)    NOT NULL,                
    item_name            VARCHAR2(100)  DEFAULT 'Unknown' NOT NULL,
    item_unit_price      NUMBER(8,2)    DEFAULT 0         NOT NULL,
    item_status          VARCHAR2(12)   DEFAULT 'Unknown' NOT NULL,
    category_id          VARCHAR2(4)    DEFAULT 'UNKN'    NOT NULL,
    category_name        VARCHAR2(50)   DEFAULT 'Unknown' NOT NULL,
    supplier_id          VARCHAR2(5)    DEFAULT 'UNKN'    NOT NULL,
    supplier_name        VARCHAR2(100)  DEFAULT 'Unknown' NOT NULL,
    supplier_contact_no  VARCHAR2(15)   DEFAULT 'Unknown' NOT NULL,
    etl_batch_id         NUMBER(8)      NOT NULL,
    etl_load_dt          DATE           DEFAULT SYSDATE   NOT NULL,
    etl_update_dt        DATE,
    dq_flag              CHAR(1)        DEFAULT 'V'       NOT NULL,
    CONSTRAINT item_dim_pk PRIMARY KEY (item_key),
    CONSTRAINT item_dim_item_id_uq UNIQUE (item_id),
    CONSTRAINT chk_item_dim_status
        CHECK (item_status IN ('Pending QC','Active','Discontinued','Unknown')),
    CONSTRAINT chk_item_dim_price  CHECK (item_unit_price >= 0),
    CONSTRAINT chk_item_dim_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  4. BRANCH_DIM  (Type 1)
--     Source : Branch  (BranchID, City, State, ContactNo only)
--     branch_name  is derived  : branch_city || ' Branch'
--     branch_region is derived : Northern      = Perlis, Kedah, Pulau Pinang, Perak
--                               Central       = Selangor, Kuala Lumpur,
--                                               Putrajaya, Negeri Sembilan
--                               Southern      = Melaka, Johor
--                               East Coast    = Pahang, Terengganu, Kelantan
--                               East Malaysia = Sabah, Sarawak, Labuan
--     Seeded row branch_key = -1 ('Unknown / Not Applicable') is used by
--     POINT_FACT for point redemptions, which carry no order and therefore
--     no branch.
-- ----------------------------------------------------------------------------
CREATE TABLE branch_dim
(
    branch_key         NUMBER(10)    NOT NULL,
    branch_id          VARCHAR2(5)   NOT NULL,                   
    branch_name        VARCHAR2(60)  DEFAULT 'Unknown' NOT NULL,
    branch_city        VARCHAR2(50)  DEFAULT 'Unknown' NOT NULL,
    branch_state       VARCHAR2(30)  DEFAULT 'Unknown' NOT NULL,
    branch_region      VARCHAR2(20)  DEFAULT 'Unknown' NOT NULL,
    branch_contact_no  VARCHAR2(15)  DEFAULT 'Unknown' NOT NULL,
    etl_batch_id       NUMBER(8)     NOT NULL,
    etl_load_dt        DATE          DEFAULT SYSDATE   NOT NULL,
    etl_update_dt      DATE,
    dq_flag            CHAR(1)       DEFAULT 'V'       NOT NULL,
    CONSTRAINT branch_dim_pk PRIMARY KEY (branch_key),
    CONSTRAINT branch_dim_branch_id_uq UNIQUE (branch_id),
    CONSTRAINT chk_branch_dim_region
        CHECK (branch_region IN ('Northern','Central','Southern',
                                'East Coast','East Malaysia','Unknown')),
    CONSTRAINT chk_branch_dim_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  5. ADDRESS_DIM  (Type 1)  -  ship-to geography for DELIVERY_FACT
--     Source : MemberAddress  (AddressLine, State, Postcode)
--     MemberAddress holds no City column, so address_region is derived from
--     address_state using the same mapping as BRANCH_DIM.  This lets a report
--     compare the branch that sold an order with the state it shipped to.
-- ----------------------------------------------------------------------------
CREATE TABLE address_dim
(
    address_key       NUMBER(10)     NOT NULL,
    address_id        VARCHAR2(5)    NOT NULL,                  
    address_line      VARCHAR2(150)  DEFAULT 'Unknown' NOT NULL,
    address_state     VARCHAR2(30)   DEFAULT 'Unknown' NOT NULL,
    address_postcode  CHAR(5)        DEFAULT '00000'   NOT NULL,
    address_region    VARCHAR2(20)   DEFAULT 'Unknown' NOT NULL,
    etl_batch_id      NUMBER(8)      NOT NULL,
    etl_load_dt       DATE           DEFAULT SYSDATE   NOT NULL,
    etl_update_dt     DATE,
    dq_flag           CHAR(1)        DEFAULT 'V'       NOT NULL,
    CONSTRAINT address_dim_pk PRIMARY KEY (address_key),
    CONSTRAINT address_dim_address_id_uq UNIQUE (address_id),
    CONSTRAINT chk_address_dim_region
        CHECK (address_region IN ('Northern','Central','Southern',
                                 'East Coast','East Malaysia','Unknown')),
    CONSTRAINT chk_address_dim_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  6. PROMOTION_DIM  (Type 1)
--     Source : Promotion
--     Two rows are seeded and must be distinguished:
--         promo_key =  0  'No Promotion'  - the sale genuinely had no promotion
--         promo_key = -1  'Unknown'       - the promotion reference was dirty
--                                           and could not be resolved
--     ItemPromotion.PromoPrice is item-specific and therefore belongs at fact
--     grain; it is used by the ETL to derive SALES_FACT.discount_amt and is not
--     stored in this dimension.
-- ----------------------------------------------------------------------------
CREATE TABLE promotion_dim
(
    promo_key            NUMBER(10)     NOT NULL,
    promotion_id         VARCHAR2(5)    NOT NULL,                 
    promo_name           VARCHAR2(100)  DEFAULT 'No Promotion' NOT NULL,
    discount_type        VARCHAR2(12)   DEFAULT 'None'         NOT NULL,
    discount_value       NUMBER(6,2)    DEFAULT 0              NOT NULL,
    promo_start_date     DATE           DEFAULT DATE '1900-01-01' NOT NULL,
    promo_end_date       DATE           DEFAULT DATE '9999-12-31' NOT NULL,
    promo_status         VARCHAR2(10)   DEFAULT 'None'         NOT NULL,
    promo_duration_days  NUMBER(6)      DEFAULT 0              NOT NULL,
    etl_batch_id         NUMBER(8)      NOT NULL,
    etl_load_dt          DATE           DEFAULT SYSDATE        NOT NULL,
    etl_update_dt        DATE,
    dq_flag              CHAR(1)        DEFAULT 'V'            NOT NULL,
    CONSTRAINT promotion_dim_pk PRIMARY KEY (promo_key),
    CONSTRAINT promotion_dim_promotion_id_uq UNIQUE (promotion_id),
    CONSTRAINT chk_promotion_dim_type
        CHECK (discount_type IN ('Percentage','Fixed','None','Unknown')),
    CONSTRAINT chk_promotion_dim_status
        CHECK (promo_status IN ('Active','Inactive','None','Unknown')),
    CONSTRAINT chk_promotion_dim_value    CHECK (discount_value     >= 0),
    CONSTRAINT chk_promotion_dim_duration CHECK (promo_duration_days >= 0),
    CONSTRAINT chk_promotion_dim_dates    CHECK (promo_end_date >= promo_start_date),
    CONSTRAINT chk_promotion_dim_dqflag   CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  7. RETURN_REASON_DIM  (Type 1)
--     Source : ReturnReason
--     reason_category is derived so that management can separate causes the
--     business controls from causes it does not:
--         'Fulfilment'      = Missing, Wrong Item   (picking / despatch error)
--         'Product Quality' = Broken, Expired       (stock or supplier issue)
-- ----------------------------------------------------------------------------
CREATE TABLE return_reason_dim
(
    reason_key       NUMBER(10)    NOT NULL,
    reason_id        VARCHAR2(4)   NOT NULL,                      
    reason_name      VARCHAR2(30)  DEFAULT 'Unknown' NOT NULL,
    reason_category  VARCHAR2(20)  DEFAULT 'Unknown' NOT NULL,
    etl_batch_id     NUMBER(8)     NOT NULL,
    etl_load_dt      DATE          DEFAULT SYSDATE   NOT NULL,
    etl_update_dt    DATE,
    dq_flag          CHAR(1)       DEFAULT 'V'       NOT NULL,
    CONSTRAINT return_reason_dim_pk PRIMARY KEY (reason_key),
    CONSTRAINT return_reason_dim_reason_id_uq UNIQUE (reason_id),
    CONSTRAINT chk_return_reason_dim_name
        CHECK (reason_name IN ('Missing','Broken','Expired','Wrong Item','Unknown')),
    CONSTRAINT chk_return_reason_dim_cat
        CHECK (reason_category IN ('Fulfilment','Product Quality','Unknown')),
    CONSTRAINT chk_return_reason_dim_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
--  8. DELIVERY_COMPANY_DIM  (Type 1)
--     Source : DeliveryCompany
-- ----------------------------------------------------------------------------
CREATE TABLE delivery_company_dim
(
    delivery_company_key  NUMBER(10)     NOT NULL,
    delivery_company_id   VARCHAR2(4)    NOT NULL,                
    company_name          VARCHAR2(100)  DEFAULT 'Unknown' NOT NULL,
    company_contact_no    VARCHAR2(15)   DEFAULT 'Unknown' NOT NULL,
    etl_batch_id          NUMBER(8)      NOT NULL,
    etl_load_dt           DATE           DEFAULT SYSDATE   NOT NULL,
    etl_update_dt         DATE,
    dq_flag               CHAR(1)        DEFAULT 'V'       NOT NULL,
    CONSTRAINT delivery_company_dim_pk PRIMARY KEY (delivery_company_key),
    CONSTRAINT delivery_company_dim_id_uq UNIQUE (delivery_company_id),
    CONSTRAINT chk_dlv_company_dim_dqflag CHECK (dq_flag IN ('V','S','D'))
);


-- ============================================================================
--  SECTION 2 : FACT TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
--  9. SALES_FACT   (Transaction fact)
--     GRAIN  : one row per item line per order
--     SOURCE : OrderDetails, joined to Orders and ItemPromotion
--
--     Measures
--       quantity      additive
--       unit_price     non-additive  (average it, never sum it)
--       gross_sales_amt  additive     = quantity * unit_price
--       discount_amt   additive      = (unit_price - PromoPrice) * quantity,
--                                     0 when no promotion applies
--       net_sales_amt   additive      = gross_sales_amt - discount_amt
--
--     sales_fact_grain_uq enforces the declared grain.  It is required
--     because CUSTOMER_DIM is Type 2: if an order were re-read after the
--     customer changed version, the composite primary key alone would accept
--     the same order line a second time under a new customer_key and revenue
--     would be double counted.
--
--     Cost and gross-profit measures are omitted: the operational system
--     records no cost column anywhere.  Profitability is analysed through
--     discount leakage and net-of-returns revenue instead.
-- ----------------------------------------------------------------------------
CREATE TABLE sales_fact
(
    order_date_key   NUMBER(8)     NOT NULL,
    customer_key     NUMBER(10)    NOT NULL,
    item_key         NUMBER(10)    NOT NULL,
    branch_key       NUMBER(10)    NOT NULL,
    promo_key        NUMBER(10)    NOT NULL,
    order_no         VARCHAR2(8)   NOT NULL,
    order_type       VARCHAR2(10)  NOT NULL,
    order_hour       NUMBER(2)     NOT NULL,
    quantity         NUMBER(4)     NOT NULL,
    unit_price       NUMBER(8,2)   NOT NULL,
    gross_sales_amt  NUMBER(10,2)  NOT NULL,
    discount_amt     NUMBER(10,2)  DEFAULT 0 NOT NULL,
    net_sales_amt    NUMBER(10,2)  NOT NULL,
    etl_batch_id     NUMBER(8)     NOT NULL,
    etl_load_dt      DATE          DEFAULT SYSDATE NOT NULL,
    etl_update_dt    DATE,
    dq_flag          CHAR(1)       DEFAULT 'V' NOT NULL,
    CONSTRAINT sales_fact_pk PRIMARY KEY
        (order_date_key, customer_key, item_key, branch_key, promo_key, order_no),
    CONSTRAINT sf_date_fk     FOREIGN KEY (order_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT sf_customer_fk FOREIGN KEY (customer_key)
                              REFERENCES customer_dim (customer_key),
    CONSTRAINT sf_item_fk     FOREIGN KEY (item_key)
                              REFERENCES item_dim (item_key),
    CONSTRAINT sf_branch_fk   FOREIGN KEY (branch_key)
                              REFERENCES branch_dim (branch_key),
    CONSTRAINT sf_promo_fk    FOREIGN KEY (promo_key)
                              REFERENCES promotion_dim (promo_key),
    CONSTRAINT sales_fact_grain_uq UNIQUE (order_no, item_key),
    CONSTRAINT chk_sales_fact_order_type
        CHECK (order_type IN ('Online','Walk-in')),
    CONSTRAINT chk_sales_fact_hour     CHECK (order_hour BETWEEN 0 AND 23),
    CONSTRAINT chk_sales_fact_qty      CHECK (quantity      > 0),
    CONSTRAINT chk_sales_fact_price    CHECK (unit_price     >= 0),
    CONSTRAINT chk_sales_fact_gross    CHECK (gross_sales_amt >= 0),
    CONSTRAINT chk_sales_fact_discount CHECK (discount_amt   >= 0),
    CONSTRAINT chk_sales_fact_net      CHECK (net_sales_amt   >= 0),
    CONSTRAINT chk_sales_fact_dqflag   CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
-- 10. RETURN_FACT   (Transaction fact)
--     GRAIN  : one row per returned item line
--     SOURCE : ReturnDetails, joined to Returns and Orders
--
--     Measures
--       quantity_returned  additive
--       refund_amount      additive
--       days_to_return      non-additive  (average it, never sum it)
--
--     order_date_key is DATE_DIM in a second role (the original order date),
--     which allows returns to be aged against the sale.
--     branch_key is the branch that SOLD the item: the Returns table carries
--     no BranchID, so it is inherited from the originating order.
--     promo_key is inherited from the matching sales line so that promotion
--     performance can be measured net of returns.
-- ----------------------------------------------------------------------------
CREATE TABLE return_fact
(
    return_date_key    NUMBER(8)     NOT NULL,
    order_date_key     NUMBER(8)     NOT NULL,
    customer_key       NUMBER(10)    NOT NULL,
    item_key           NUMBER(10)    NOT NULL,
    branch_key         NUMBER(10)    NOT NULL,
    reason_key         NUMBER(10)    NOT NULL,
    promo_key          NUMBER(10)    NOT NULL,
    return_id          VARCHAR2(8)   NOT NULL,
    order_no           VARCHAR2(8)   NOT NULL,
    return_status      VARCHAR2(10)  NOT NULL,
    quantity_returned  NUMBER(4)     NOT NULL,
    refund_amount      NUMBER(10,2)  NOT NULL,
    days_to_return     NUMBER(6)     DEFAULT 0 NOT NULL,
    etl_batch_id       NUMBER(8)     NOT NULL,
    etl_load_dt        DATE          DEFAULT SYSDATE NOT NULL,
    etl_update_dt      DATE,
    dq_flag            CHAR(1)       DEFAULT 'V' NOT NULL,
    CONSTRAINT return_fact_pk PRIMARY KEY
        (return_date_key, customer_key, item_key, branch_key,
         reason_key, return_id),
    CONSTRAINT rf_retdate_fk  FOREIGN KEY (return_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT rf_orddate_fk  FOREIGN KEY (order_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT rf_customer_fk FOREIGN KEY (customer_key)
                              REFERENCES customer_dim (customer_key),
    CONSTRAINT rf_item_fk     FOREIGN KEY (item_key)
                              REFERENCES item_dim (item_key),
    CONSTRAINT rf_branch_fk   FOREIGN KEY (branch_key)
                              REFERENCES branch_dim (branch_key),
    CONSTRAINT rf_reason_fk   FOREIGN KEY (reason_key)
                              REFERENCES return_reason_dim (reason_key),
    CONSTRAINT rf_promo_fk    FOREIGN KEY (promo_key)
                              REFERENCES promotion_dim (promo_key),
    CONSTRAINT return_fact_grain_uq UNIQUE (return_id, order_no, item_key),
    CONSTRAINT chk_return_fact_status
        CHECK (return_status IN ('Pending','Approved','Rejected','Refunded')),
    CONSTRAINT chk_return_fact_qty    CHECK (quantity_returned > 0),
    CONSTRAINT chk_return_fact_refund CHECK (refund_amount    >= 0),
    CONSTRAINT chk_return_fact_days   CHECK (days_to_return    >= 0),
    CONSTRAINT chk_return_fact_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
-- 11. DELIVERY_FACT   (Transaction fact)
--     GRAIN  : one row per delivery
--     SOURCE : Delivery, joined to Orders
--
--     Measures
--       delivery_charge    additive
--       order_total_amount  additive     (safe at this grain: Delivery.OrderNo
--                                        is UNIQUE, so one delivery per order)
--       delivery_lead_days  non-additive  = DeliveryDate - OrderDateTime,
--                                        NULL until the order is delivered
--
--     Delivery.DeliveryDate is NULL until despatch completes, so pending and
--     cancelled deliveries carry delivery_date_key = -1 (the seeded Unknown
--     date).  Keeping them in the fact allows the pending and cancellation
--     rate per courier to be reported, rather than silently dropping them.
-- ----------------------------------------------------------------------------
CREATE TABLE delivery_fact
(
    delivery_date_key     NUMBER(8)     NOT NULL,
    order_date_key        NUMBER(8)     NOT NULL,
    customer_key          NUMBER(10)    NOT NULL,
    branch_key            NUMBER(10)    NOT NULL,
    delivery_company_key  NUMBER(10)    NOT NULL,
    address_key           NUMBER(10)    NOT NULL,
    delivery_id           VARCHAR2(8)   NOT NULL,
    order_no              VARCHAR2(8)   NOT NULL,
    delivery_status       VARCHAR2(15)  NOT NULL,
    delivery_charge       NUMBER(6,2)   DEFAULT 0 NOT NULL,
    order_total_amount    NUMBER(10,2)  DEFAULT 0 NOT NULL,
    delivery_lead_days    NUMBER(6),
    etl_batch_id          NUMBER(8)     NOT NULL,
    etl_load_dt           DATE          DEFAULT SYSDATE NOT NULL,
    etl_update_dt         DATE,
    dq_flag               CHAR(1)       DEFAULT 'V' NOT NULL,
    CONSTRAINT delivery_fact_pk PRIMARY KEY
        (delivery_date_key, customer_key, branch_key,
         delivery_company_key, address_key, delivery_id),
    CONSTRAINT df_dlvdate_fk  FOREIGN KEY (delivery_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT df_orddate_fk  FOREIGN KEY (order_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT df_customer_fk FOREIGN KEY (customer_key)
                              REFERENCES customer_dim (customer_key),
    CONSTRAINT df_branch_fk   FOREIGN KEY (branch_key)
                              REFERENCES branch_dim (branch_key),
    CONSTRAINT df_company_fk  FOREIGN KEY (delivery_company_key)
                              REFERENCES delivery_company_dim (delivery_company_key),
    CONSTRAINT df_address_fk  FOREIGN KEY (address_key)
                              REFERENCES address_dim (address_key),
    CONSTRAINT delivery_fact_grain_uq UNIQUE (delivery_id),
    CONSTRAINT chk_delivery_fact_status
        CHECK (delivery_status IN ('Pending','In Transit','Delivered','Cancelled')),
    CONSTRAINT chk_delivery_fact_charge CHECK (delivery_charge   >= 0),
    CONSTRAINT chk_delivery_fact_total  CHECK (order_total_amount >= 0),
    CONSTRAINT chk_delivery_fact_lead   CHECK (delivery_lead_days >= 0),
    CONSTRAINT chk_delivery_fact_dqflag CHECK (dq_flag IN ('V','S','D'))
);

-- ----------------------------------------------------------------------------
-- 12. POINT_FACT   (Transaction fact)
--     GRAIN  : one row per loyalty point transaction
--     SOURCE : PointTransaction
--
--     Measures
--       points_earned    additive
--       points_redeemed  additive
--       net_points       additive  = points_earned - points_redeemed
--
--     The source stores a single positive Point value and carries the sign in
--     PointTransaction.TransType.  Splitting it into two measures lets earn and redeem be
--     summed independently without a CASE expression at query time, and
--     SUM(net_points) per customer reproduces Member.PointsBalance - which is
--     the reason PointsBalance is not stored in CUSTOMER_DIM.
--
--     chk_pointtrans_order in the source enforces that an 'Earn' row has an
--     OrderNo and a 'Redeem' row does not.  Redemptions therefore have no
--     order and no branch: order_no is NULL and branch_key points at the
--     seeded branch_key = -1 'Unknown / Not Applicable' row, which keeps the
--     fact uniform and every dimension join valid.
-- ----------------------------------------------------------------------------
CREATE TABLE point_fact
(
    trans_date_key   NUMBER(8)     NOT NULL,
    customer_key     NUMBER(10)    NOT NULL,
    branch_key       NUMBER(10)    NOT NULL,
    point_trans_id   VARCHAR2(7)   NOT NULL,
    order_no         VARCHAR2(8),
    trans_type       VARCHAR2(10)  NOT NULL,
    points_earned    NUMBER(8)     DEFAULT 0 NOT NULL,
    points_redeemed  NUMBER(8)     DEFAULT 0 NOT NULL,
    net_points       NUMBER(9)     DEFAULT 0 NOT NULL,
    etl_batch_id     NUMBER(8)     NOT NULL,
    etl_load_dt      DATE          DEFAULT SYSDATE NOT NULL,
    etl_update_dt    DATE,
    dq_flag          CHAR(1)       DEFAULT 'V' NOT NULL,
    CONSTRAINT point_fact_pk PRIMARY KEY
        (trans_date_key, customer_key, branch_key, point_trans_id),
    CONSTRAINT pf_date_fk     FOREIGN KEY (trans_date_key)
                              REFERENCES date_dim (date_key),
    CONSTRAINT pf_customer_fk FOREIGN KEY (customer_key)
                              REFERENCES customer_dim (customer_key),
    CONSTRAINT pf_branch_fk   FOREIGN KEY (branch_key)
                              REFERENCES branch_dim (branch_key),
    CONSTRAINT point_fact_grain_uq UNIQUE (point_trans_id),
    CONSTRAINT chk_point_fact_type
        CHECK (trans_type IN ('Earn','Redeem')),
    CONSTRAINT chk_point_fact_earned   CHECK (points_earned   >= 0),
    CONSTRAINT chk_point_fact_redeemed CHECK (points_redeemed >= 0),
    CONSTRAINT chk_point_fact_net      CHECK (net_points = points_earned - points_redeemed),
    CONSTRAINT chk_point_fact_order
        CHECK ((trans_type = 'Earn'   AND order_no IS NOT NULL) OR
               (trans_type = 'Redeem' AND order_no IS NULL)),
    CONSTRAINT chk_point_fact_dqflag   CHECK (dq_flag IN ('V','S','D'))
);

-- ============================================================================
--  END OF TASK 1(b) PHYSICAL DESIGN
-- ============================================================================